fcitx-contrib/fcitx5-macos

- macosnotifications/macosnotifications.cpp
- src/fcitx.cpp
- src/fcitx.h
No longer need to supply the return type.
> Improve the with_fcitx template

- include/fcitx-public.h
- macosfrontend/macosfrontend.cpp
- macosfrontend/macosfrontend.h
- macosnotifications/macosnotifications.cpp
- src/config/menu.swift
- src/controller.swift
- src/fcitx.cpp
- src/fcitx.h
~Must be tested after `cmake --install`.~
~Tested by removing `~/.local/share/fcitx5/rime` then clicking `Force Restart` in menu. See Rime redeployment.~
Click `Restart` in menu. See Rime redeployment and no PID change for Fcitx5.
> restart thread

- include/fcitx-public.h
- src/controller.swift
- src/fcitx.cpp
~~I can't get submenus to work properly though.~~ Flattened now.
A long rime menu:
> status area actions

- dmg/CMakeLists.txt
- install-deps.sh
- macosnotifications/macosnotifications.cpp
- macosnotifications/macosnotifications.h
- macosnotifications/notify.swift
> Attach appIcon to notifications

- .github/workflows/ci.yml
- CMakeLists.txt
- cmake/AddSwift.cmake
- fix-cross-build.sh
- logging/CMakeLists.txt
- logging/logging.swift
- macosnotifications/CMakeLists.txt
- macosnotifications/notify.swift
- src/CMakeLists.txt
- src/controller.swift
Tested by seeing `Notification permission is granted` in Console after killing and restarting Fcitx5.
> Use OSLog instead of NSLog

- .gitmodules
- CMakeLists.txt
- deps/CMakeLists.txt
- src/CMakeLists.txt
- src/config/config-public.h
- src/config/config.cpp
- src/config/config.h
- src/config/config.swift
- src/config/globalconfig.swift
- src/config/menu.swift
- src/config/optionmodels.swift
- src/config/optionviews.swift
- src/controller.swift
- src/fcitx.cpp
- src/fcitx.h
- src/module.modulemap
Click `Print` to see updated values in stdout.
Some known issues:
- Lists are invisible in ScrollView
- Element order unstable
- Key not supported (will need https://github.com/Kentzo/ShortcutRecorder)
They will be addressed in later PRs.
> feat(config): Views

- src/config/plugin.swift
Tested no shared files removed, by putting a.json
```json
{"files": ["share/a", "share/s"]}
```
and b.json
```json
{"files": ["share/b", "share/s"]}
```
in `~/Library/fcitx5/plugin`, and `touch a b s` in `~/Library/fcitx5/share`.
Removing only a should keep `s` and `b` there, then removing b should remove them.
Removing a and b together removes `a` `b` and `s`.
Also tested wrong json format, no `files` key, `files` is not an array of string.
> uninstall plugins

- .github/workflows/ci.yml
- src/CMakeLists.txt
- tests/CMakeLists.txt
Swift files are repeated sometimes because the interfaces are required.
> ci: enable tests

- macosfrontend/macosfrontend.cpp
- macosfrontend/macosfrontend.h
Test procedure should be the same with https://github.com/fcitx-contrib/fcitx5-macos/pull/48
> use FocusGroup

- src/config/plugin.swift
Remember to clear `~/Library/fcitx5/cache`.
(Optional) To test locally,
```
brew install nginx
brew services start nginx
```
Modify `/usr/local/etc/nginx/nginx.conf` by adding
```nginx
location ~\.bz2$ {
root /path/to/fcitx5-macos-plugins/build;  # directory that contains *.tar.bz2
limit_rate 500k;  # bytes per second
}
```
before
```nginx
location / {
root   html;
index  index.html index.htm;
}
```
then `nginx -s reload`.
> show plugin download progress

- src/config/inputmethod.swift
https://github.com/fcitx-contrib/fcitx5-macos/assets/23358293/71b0efde-68a4-4af2-ac11-898d55ff8b51
"remove group" is kept in context menu to prevent mistakes
> config: Show + and - buttons to add/remove on hover

- CMakeLists.txt
- macosfrontend/macosfrontend.cpp
- macosfrontend/macosfrontend.h
- src/CMakeLists.txt
- src/fcitx.cpp
- webpanel/CMakeLists.txt
- webpanel/webpanel.conf.in.in
- webpanel/webpanel.cpp
- webpanel/webpanel.h
~~Currently, only Layout and Theme are configurable. Currently, they do not work after restarting because `updateConfig` is run before the webview initialization. Will create a follow-up PR in the fcitx5-webview repo soon.~~ Done
> Refactor the panel code into a standalone UI addon

- src/config/addonconfig.swift
- src/config/globalconfig.swift
- src/config/inputmethod.swift
- src/config/optionviews.swift
Unify buttons everywhere.
Tested Input Methods, Global and Addon.
> config buttons: reset to default, apply, save

- src/config/inputmethod.swift
- src/config/optionviews.swift
It's now possible to wrap long texts, and we get more flexibility in layout.
> config: Replace Form by Grid

- webpanel/webpanel.h
> ui config: border and horizontal divider

- webpanel/webpanel.h
Support whatever you can put in `background-image: url("xxx")`.
> ui config: background image

- src/config/config.swift
- src/config/optionmodels.swift
- src/config/optionviews.swift
- webpanel/webpanel.h
> ui config: font

- webpanel/webpanel.cpp
- webpanel/webpanel.h
> ui config: cursor

- webpanel/webpanel.h
> ui config: highlight margin/padding/corner

- webpanel/webpanel.cpp
- webpanel/webpanel.h
> ui config: mark bar/text

- macosfrontend/macosfrontend.cpp
- macosfrontend/macosfrontend.h
- src/config/config.swift
- src/config/optionmodels.swift
- src/config/optionviews.swift
https://github.com/fcitx/fcitx5/issues/49
> set default im for app

- webpanel/webpanel.h
https://github.com/fcitx-contrib/fcitx5-macos/assets/26783539/a36743e2-e9be-4a7e-be62-98db2a0b4e62
> ui config: highlight color on hover and text color on press

- src/config/addonconfig.swift
- src/config/globalconfig.swift
- src/config/inputmethod.swift
- src/config/optionviews.swift
- src/config/plugin.swift
make "OK" buttons use the accent color.
> Set button roles and styles for special buttons

- .gitignore
- README.md
- src/CMakeLists.txt
- src/config/about.swift
- src/config/meta.swift.in
- src/config/plugin.swift
- src/config/ui.swift
> formalize about window

- assets/CMakeLists.txt
- assets/uninstall.sh
- src/config/about.swift
- src/config/sudo.swift
We should do better than Squirrel.
https://github.com/rime/home/issues/59
> implement uninstall

- webpanel/webpanel.cpp
- webpanel/webpanel.h
> config ui: paging buttons

- webpanel/webpanel.cpp
- webpanel/webpanel.h
> separate text and comment

- macosfrontend/keycode.cpp
> add missing keysym mappings

- .gitignore
- README.md
- logging/CMakeLists.txt
- logging/debug.swift.in
- logging/logging.swift
- src/nativestreambuf.h
- src/server.swift
> Write log and stderr to /tmp/Fcitx5.log; disable OSLog and debug log for release build

- src/config/config.swift
- src/config/optionviews.swift
> opencc config dropdown

- src/config/about.swift
- src/config/downloader.swift
- src/config/plugin.swift
Test procedure:
Edit some `~/Library/fcitx5/plugin/*.json` to clear `version` fields, then update in About.
After IM restart, the missing `version` fields should be filled.
> refactor plugin download; update all plugins on main update

- webpanel/webpanel.cpp
Tested pin, unpin and forget with the latest chinese-addons.
> context menu

- macosfrontend/macosfrontend.cpp
> fix ， not committed immediately when , after number/english is deleted

- assets/po/zh_CN.po
- webpanel/webpanel.cpp
- webpanel/webpanel.h
https://github.com/fcitx-contrib/fcitx5-macos/assets/26783539/2aaa763a-a043-4001-91ad-75e0d5d4c045
Previous feature requests that are not implemented yet:
https://github.com/rime/squirrel/issues/318
https://github.com/rime/weasel/issues/1005
https://github.com/fcitx/fcitx5/issues/902
> scroll mode 📜 卷轴模式

- assets/po/zh_CN.po
- webpanel/webpanel.h
> apply min-width for vertical mode

- macosfrontend/macosfrontend.cpp
> fix hang when copying HTML content

- assets/po/zh_CN.po
- webpanel/webpanel.cpp
- webpanel/webpanel.h
Test: same with https://github.com/fcitx-contrib/fcitx5-macos-plugins/pull/44
> fix Hyper resets rime scroll mode

- src/config/inputmethod.swift
- src/fcitx.cpp
I don't know why. It works. Although removing a group still crashes.
> fix im config crash on macOS 15 arm

- .github/workflows/ci.yml
- src/config/datamanager.swift
Suddenly a user and I can't import zip. I rebuild both release and debug. I can import. I downgrade to current ci build. I can still import. Who knows why.
> try fixing import zip

- macosfrontend/macosfrontend.swift
- src/controller.swift
Fixes #207
commit doesn't cause stall. Only set preedit may.
> set preedit only when has cursor

- macosfrontend/macosfrontend.h
> Passwords.app uses keyboard-us

- .github/workflows/ci.yml
- src/config/optionmodels.swift
> fix: non-rgb slider

- macosfrontend/macosfrontend.cpp
- macosfrontend/macosfrontend.swift
> don't set preedit on async commit

- assets/po/zh_CN.po
- webpanel/webpanel.cpp
- webpanel/webpanel.h
Closes #222
https://github.com/user-attachments/assets/d3a7970e-03ff-47a4-b9c3-6e9ea6907645
> scroll mode expand/collapse animation

- .vscode/settings.json
- assets/po/zh_CN.po
- webpanel/webpanel.cpp
- webpanel/webpanel.h
> configurable select candidate keys in scroll mode

- macosfrontend/macosfrontend.swift
causes Word issue; unnecessary since 5ffb9bf7d746b11d49f0e40c046a03e5a8d47412
Fixes #248
> revert 9bfd58f28e04d22f20cee6a9d25b2789a637b483

- assets/po/zh_CN.po
- macosfrontend/macosfrontend.cpp
- macosfrontend/macosfrontend.h
- src/config/appimoptionview.swift
- src/config/config.swift
- src/config/optionmodels.swift
- src/config/optionviews.swift
- src/config/ui.swift
- src/config/util.swift
- src/config/vimmodeoptionview.swift
- tests/CMakeLists.txt
> support vim mode
