.github/workflows/ci.yml, CMakeLists.txt, README.md
On my M1 mac, pkgconfig locates expat.h under `/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include` which also contains headers of C standard lib, which shouldn't be searched before headers of C++ standard lib.
=> don't use system expat

.github/workflows/ci.yml, include/fcitx.h, macosfrontend/macosfrontend.cpp, macosfrontend/macosfrontend.h, src/controller.swift, src/fcitx.cpp, src/keycode.cpp
use rime to test
+ `shift` to toggle `ascii_mode`
+ `shift+fn+delete` to delete user words
+ correctly send keys like `ctrl+b` `ctrl-m` to fcitx-rime
+ special keys (return, tab, esc, etc.) still work
+ `shift+a` still sends `A`
=> Handle modifier keys

macosfrontend/macosfrontend.cpp, src/fcitx.swift
By default, the preedit cursor is fixed to be 0, so make sure to put `PreeditCursorPositionAtBeginning=False` in the conf file.
=> Fix caret display in client preedit

include/fcitx-public.h, src/controller.swift, src/fcitx.cpp, src/fcitx.h
Example profile:
```
[Groups/0]
Name=Main
Default Layout=us
DefaultIM=pinyin
[Groups/0/Items/0]
Name=rime
Layout=us
[Groups/0/Items/1]
Name=pinyin
Layout=us
[Groups/1]
Name=Other
Default Layout=us
DefaultIM=shuangpin
[Groups/1/Items/0]
Name=shuangpin
Layout=us
[Groups/1/Items/1]
Name=rime
Layout=us
[GroupOrder]
0=Main
1=Other
```
Result:
The first section (group switcher) will be hidden if there is only one group.
=> Input method switcher

src/fcitx.h
My fault. PanelShowFlags was not properly cleared, so every keystroke will show the candidate window.
This also fixes the cmd-v lag. Probable cause:
- cmd-v → f5m: f5m rejects it, but also initiates an async panel show (it won't after this PR)
- cmd-v → program: program initiates paste
- async panel show triggers `client.attributes` and they clash
=> Remove unnecessary panel display

macosfrontend/macosfrontend.conf.in.in, macosfrontend/macosfrontend.cpp, macosfrontend/macosfrontend.h
Support chord typing in rime.
This is by default disabled. To enable, modify `~/.config/fcitx5/conf/macosfrontend.conf`:
```
SimulateKeyRelease=True
SimulateKeyReleaseDelay=100
```
=> Simulate key release

CMakeLists.txt, cmake/MacOSXBundleInfo.plist.in, src/config/config-public.h, src/config/config.cpp, src/config/config.swift, src/config/globalconfig.swift, src/config/inputmethod.swift, src/config/menu.swift, src/config/optionmodels.swift, src/config/optionviews.swift, src/controller.swift, src/fcitx-public.h, src/fcitx.cpp, src/fcitx.h, tests/CMakeLists.txt, tests/testconfig.cpp, tests/testconfig.swift
This PR primarily adds the input method config tool:
Input methods (and groups) can now be:
1. queried, listed: by default
2. added: to add an IM, right click on the name of a group and select "Add input method"; to add a group, right click on the unused area and select "Add group".
3. removed: to remove an IM, right click on the IM and select "Remove input method"; to remove a group, right click on the name of a group and select "Remove group".
4. reordered: just drag and drop
the config can be loaded, changed, and saved.
A screen recording demonstrating adding and changing shuangpin settings:
https://github.com/fcitx-contrib/fcitx5-macos/assets/23358293/49acd704-8882-4cc3-975c-f81a5a803eec
Other assorted changes:
- Added `tests`. It currently relies on locally installed plugins, so CI …
=> feat(config): Input method

cmake/MacOSXBundleInfo.plist.in, src/config/globalconfig.swift, src/config/inputmethod.swift, src/config/menu.swift
Revert #36's Info.plist change. Still default to LSBackground, but switch to regular activation policy when there is at least one config window.
=> Dynamic switching of activation policies

macosfrontend/macosfrontend.cpp, src/config/menu.swift, src/controller.swift
- After restarting, observe "Reconnecting" debugging logs.
- Quit some apps, and the "Reconnecting" messages for these apps also disappear, meaning the input controllers are successfully reclaimed.
=> Recreate fcitx input contexts after restarting

src/config/config.swift, src/config/optionviews.swift
The subgroups are now in a group box:
This matches the appearance of the upstream fcitx-configtool.
=> Use GroupBox for config subgroups

src/controller.swift
Reproduce:
Open Shotcut, drag a video from Finder to timeline, press space to play.
=> fix pressing space to play not work in shotcut

cmake/MacOSXBundleInfo.plist.in
Tested scenarios:
* In built-in Terminal, type `sudo ls`, switch to double pinyin, hit return.
* master: Fcitx5 is still used, and backspace won't clear candidate window.
* PR: fall back to ABC, and Fcitx5 is disabled.
* When double pinyin is activated, lock screen. Input password.
* master: although not indicated in top bar, Fcitx5 is actually used.
* PR: ABC is used.
To test this PR, you may need to logout then login, remove Fcitx5 from input method list and re-add it from Simplified Chinese.
I don't think registering for multiple languages is needed, at least for now.
Nor do I want to change background.tiff, as dmg from CI isn't usable at all.
=> register as Chinese to disable itself on password

README.md, macosfrontend/macosfrontend.cpp
Test: open 2 Terminals, type something on one but don't commit to keep candidate window open, then click the other Terminal.
Previous: candidate window is still there, but clicking/pressing space after switching back to the terminal won't commit anything.
Current: candidate window disappears.
=> fix: close candidate window on deactivate

.github/workflows/ci.yml, .swift-format.json, src/config/optionmodels.swift, src/config/optionviews.swift
(↑ `List|Key` currently displayed as string list.)
Elements can be added, removed, reordered, and edited. `Save` also works. For example: swap `minus` and `equalsign` in "Prev cand" and "Next cand"; add `semicolon` as "Select second cand"; add `apostrophe` as "Select third cand". After saving, these keys will work.
=> config: List views

macosfrontend/macosfrontend.cpp, src/config/inputmethod.swift, src/config/menu.swift, src/config/plugin.swift, src/fcitx.cpp
Caveats for reviewer to try and confirm:
* For `viewModel` to auto update view, it has to be a `ObservedObject` instead of `StateObject`.
* `dispatcher_->attach` has to be executed in main thread to ensure it's executed before https://github.com/fcitx-contrib/fcitx5-macos/blob/54a78bb2562b82591606eddee0466bc71447816c/src/fcitx.h#L57
otherwise `fut.wait()` may hang. This may happen when you install a plugin and type in another window at the same time.
Normal test procedure:
* Open Input Methods, see no Thai IM in Thai Lang. Close.
* Install thai in Plugin Manager.
* Reopen Input Methods and add Thai IM. Confirm it works by `l;ylfu` which is สวัสดี. Close.
* Uninstall thai.
* Reopen Input Methods and see Thai disappear.
=> auto restart on plugin install/uninstall

src/config/inputmethod.swift
- before: if there are multiple groups, after adding an input method, the dialog will flash many times
- after: this behavior is corrected
=> fix: repeated dialog appearance

src/config/inputmethod.swift
fix "Bug: changing input methods order doesn't affect their order in system menu"
=> fix(config): save input method info after reorder

macosfrontend/macosfrontend.h, src/CMakeLists.txt, src/config/addonconfig.swift, src/config/menu.swift, src/config/optionviews.swift, src/controller.swift, src/fcitx-public.h, src/fcitx.cpp
Reference:
* Producer: https://github.com/fcitx/fcitx5/blob/b8d5038913b4227c5ca72d7c7ed80cab32f6b39d/src/modules/dbus/dbusmodule.cpp#L445
* Consumer: https://github.com/fcitx/fcitx5-configtool/blob/39d826e6f818c7c7df05f3861bb52ad44c4d351c/src/lib/configlib/addonmodel.cpp#L27
Test:
* Rime: `Fix embedded preedit cursor at the beginning of preedit` works.
* macOS Frontend: `Simulate key release` works.
I only reused view model. If view (sheet) could be reused that would be better.
=> implement addon config

.github/workflows/ci.yml, src/config/addonconfig.swift, src/config/inputmethod.swift, src/config/optionviews.swift
Reproduce: drag window horizontally so that horizontal scrollbar disappears, then clicking checkbox won't get a response. The actual click region that can respond is shifted right.
Horizontal scroll itself is usually bad UX anyway, so worth making a rule.
=> disallow horizontal ScrollView

macosfrontend/macosfrontend.cpp, macosfrontend/macosfrontend.h
An attempt to fix a race condition about focusin and focusout on the same IC, experienced in Telegram: sometimes focusOut will be sent after focusIn on the same IC. This PR fully delegates the work of `activeIC_` to `FocusGroup`, and makes sure the IC is focused in when handling keyEvent.
=> fix focusIn->focusOut on the same IC

src/config/config.swift, src/config/optionmodels.swift, src/config/optionviews.swift, webpanel/webpanel.h
Hack: a `ColorOption` maps to a `ColorPicker` and a `TextField`.
Ideally more code could be reused from IntegerOptionView for alpha, but given we aim to remove the hack later, it's not worth over-engineering right now.
=> ui config: highlight color and panel color

macosfrontend/macosfrontend.cpp, macosfrontend/macosfrontend.h, webpanel/webpanel.cpp
To reproduce on master, set `Preedit Mode` to `Do not show` in rime, then confirm that Backspace bypasses IM in Terminal, and there is an annoying echo in iTerm.
=> force a dummy client preedit

src/config/config.swift, src/config/optionmodels.swift, src/config/optionviews.swift
Parametrize `ListOptionView` by `Option` instead of the underlying storage types, which should make supporting other element types easier. Adding empty elements is handled by adding a new protocol `EmptyConstructible`.
=> config: support List|Enum

src/config/inputmethod.swift, src/config/optionviews.swift, src/config/plugin.swift
I don't think it a good idea to double click to uninstall so keep it as-is.
Refactored `AvailableInputMethodView` to let view model handle more states, but didn't find a way to keep "IMs in current group" synced when current sheet is still open, so added a hack comment.
=> double click to add IM, set font and install plugin

src/fcitx.cpp
Reproduce: make sure there is only one group, uninstall hallelujah plugin, install hallelujah plugin, switch to hallelujah, use it, `pkill Fcitx5`, then hallelujah disappears from current IM list.
=> fix auto-added im not saved

webpanel/webpanel.cpp
Reproduce: disable client preedit, type a 2-char word but only click a single-char candidate, ui isn't updated.
=> fix click partial candidate not update ui when no client preedit

src/config/optionviews.swift
This is something that needs to be handled but I don't know the best practice so feel free to change to a better solution.
On master when you want to set font size to 30 you type 3 first, but since it's less than 4, it's automatically converted to 4, which is bad UX.
=> fix forcing the leading 3 of 30 to be 4 when int option is 4 to 100

webpanel/webpanel.cpp, webpanel/webpanel.h
This is Move mode, same with fcitx5 Linux.
https://github.com/fcitx-contrib/fcitx5-macos/assets/26783539/c352d995-4f59-473d-87a2-e5f5cc8c6cad
This is Add mode, same with MSPY.
https://github.com/fcitx-contrib/fcitx5-macos/assets/26783539/857ea75a-60a2-4b7a-88c7-b99113a09d7e
=> ui config: hover behavior of 3 desktop OSs

src/config/about.swift, src/config/menu.swift
master: Input Method is frontmost but not focused. Global config is neither. About doesn't even have an icon in dock.
PR: all frontmost and focused.
=> focus config window on open

.github/workflows/ci.yml, assets/CMakeLists.txt, assets/switch_im.swift, assets/update.sh, src/config/about.swift, src/config/menu.swift, src/config/plugin.swift
For every sheet, ESC and OK have the same effect.
Test procedure:
* Set src/config/meta.swift so that commit is the same with master, rebuild.
* Turn off network, Check update, Failed to check update.
* Turn on network, Check update, Fcitx5 is up to date. Button is disabled. Reopen about could reenable it.
* Rebuild. Check update, Maybe later, the button should be Update, and remains on reopen.
* Update, but cancel sudo password, should prompt error.
* Update with password, about window should quit, but you should be able to use the updated version seamlessly.
=> in-app update

webpanel/webpanel.cpp
=> hack: trim label end as linux ui impl specific

macosfrontend/keycode.cpp, macosfrontend/keycode.h, macosfrontend/macosfrontend.cpp
fixes #101
also tested with other input methods
=> send capital keysym when a-z is shift-modified

macosfrontend/macosfrontend-public.h, macosfrontend/macosfrontend.cpp, macosfrontend/macosfrontend.h, macosfrontend/macosfrontend.swift, src/controller.swift, webpanel/webpanel.cpp
Someone reports 顶功 may randomly fail after deployment with [星猫键道](https://github.com/hugh7007/xmjd6-rere).
A possible reason is
A possible solution is
It's proved that iTerm2 requires set preedit before return handled.
This may also fix candidate window jumpsing to origin when librime-predict is enabled in telegram.
Since dummy preedit implementation is changed, also need to test scenarios of #69.
=> Stabilize commit, set preedit, return handled order in main thread

.github/workflows/ci.yml, src/config/about.swift
Generate a meta.json that has the same structure of the unstable GitHub API. The accessibility of meta.json and artifact are the same so there should be no more to optimize.
For test, I've manually uploaded a meta.json to release. You should be able to downgrade to current master on this branch, and if you do `git reset --soft master` and rebuild to force master's commit sha to be used, you should see Fcitx5 is up to date.
=> replace GitHub API with meta.json

macosfrontend/macosfrontend.cpp, macosfrontend/macosfrontend.swift, src/controller.swift
I guess the problem is that IC may be destroyed before the code deferred to main thread is executed. So I make the swift function async instead of the C++ function.
While I have no guarantee that it can avoid the crash, I do believe we won't see the same stacktrace again.
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00005741e5894870
Exception Codes:       0x0000000000000001, 0x00005741e5894870
Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [742]
VM Region Info: 0x5741e5894870 is not in any region.  Bytes after previous region: 95927650568305  Bytes before following region: 3914568480656
REGION TYPE …
```
=> try fix segfault on client (async UAF?)

webpanel/webpanel.cpp, webpanel/webpanel.h
Reproduce:
* Checkout 83e214aa3f34f9be1a52aaa343fe3aac5ad798ff
* Import a .dict file in Pinyin's dict manager.
* Crash on https://github.com/fcitx-contrib/fcitx5-webview/blob/7a93ac2955c32f5df0b2b547f83cd32ec5e3374e/include/webview_candidate_window.hpp#L61 (the call is `updateInputPanel("", "", "")`)
Merge this branch to see no error.
Ref: https://chat.openai.com/share/4ecb4853-547e-4de9-9d88-11a1d0a021f7
=> use weak_ptr to avoid async uaf

README.md, assets/core.entitlements
Test:
Add `FCITX_DEBUG() << *(int *)nullptr;` to a C++ function, then follow the procedure.
Ref: https://nasa.github.io/trick/howto_guides/How-to-dump-core-file-on-MacOS.html
=> support core dump for dev

.github/workflows/ci.yml, CMakeLists.txt, README.md, assets/CMakeLists.txt, install-deps.sh
there will be no more errors that mention '/tmp/fcitx5' in the logs.
should be able to use other keyboard types without issues.
=> fix xkeyboard-config and iso-codes

assets/po/zh_CN.po, webpanel/webpanel.cpp, webpanel/webpanel.h
Known issues:
* Some emojis are rotated and some not. A WebKit issue that I'm not going to hack.
* Horizontal layout + Vertical writing mode may lead to wrong multi-character candidate's layout that is corrected on drag. Use it as-is and it's not worth investigation.
=> support vertical writing modes

src/fcitx.cpp
leftover from https://github.com/fcitx-contrib/fcitx5-macos-prebuilder/pull/33
=> fix xkb path

src/controller.swift, src/fcitx.cpp
Changing shortcut on fcitx side is reflected to menu instantly, which I'm surprised.
This has to be tested by building master fcitx5-chinese-addons locally.
=> show shortcut for command

.gitmodules, README.md, deps/CMakeLists.txt, src/CMakeLists.txt, src/config/about.swift, src/config/plugin.swift
5 less sheets that are ugly and require unnecessary user interaction.
This PR only handles replacement because I want to see a negative LoC change. Will add spin/success/failure to other scenarios.
=> integrate AlertToast

src/config/optionmodels.swift
This is a bug since day 1. The purpose of this code is to convert
```
ListOption([ val1, val2, ... ])
````
into
```
[Option(val1), Option(val2), ...]
```
The decode in the map expects JSON values, but previously `$0` is decoded value, not json value.
The old buggy code works for simple values, like integers and arrays, but not on complex custom data types, which will become `unknown` values hidden inside the outer json value, and will explode later.
=> fix list option parse

assets/po/zh_CN.po, webpanel/webpanel.cpp, webpanel/webpanel.h
A shortcut with no default for develop/customize purpose since real-time inspect is disabled by default and (when enabled) cumbersome to use.
=> copy html to clipboard

src/config/keyrecorder.swift, src/controller.swift
`NSEvent` has different `characters` and `charactersIgnoringModifiers` for IM and key recorder. 💀️
Fixes: #157
=> regression: not able to use Shift+comma to input 《

assets/po/zh_CN.po, webpanel/webpanel.cpp, webpanel/webpanel.h
f5m:
native:
Please test different layout, writing-mode and paging buttons style combinations.
=> imitate arrow paging buttons and semi-circle end

macosfrontend/macosfrontend.swift
Tested in VSCode. Shift+click to select won't clear selected text any more.
=> fix using Shift to select results in clearing selected text

macosfrontend/macosfrontend.cpp
In VSCode, fn+E to call out emoji picker, click one, type immediately and wait without commit.
Previous: candidate window disappeared.
Current: nothing happens and you can continue.
=> fix typing interrupted after picking emoji from CharacterPaletteIM

macosfrontend/macosfrontend.swift
Tested with our old friends:
* Terminal with empty clipboard: able to esc.
* Terminal with 双拼 and semicolon: able to use return to commit semicolon.
* iTerm2 with/without client preedit: no extraneous characters committed.
=> use zero width space as dummy preedit to avoid text shift

macosfrontend/macosfrontend.h, src/config/appimoptionview.swift, src/config/optionmodels.swift, src/config/optionviews.swift
These Apps are not easily found in application selector.
Also refactored model so that App path is source of truth.
=> list some preset Apps for AppIM

.gitmodules, webpanel/webpanel.cpp
Tested:
* Terminal: ; and Return can input ascii semicolon.
* Terminal: ESC can close an empty clipboard.
* LibreOffice: Shift won't clear current cell.
Please approve and wait for https://github.com/fcitx/fcitx5/pull/1085.
=> fix: don't set dummy preedit when switching IM for LibreOffice

src/config/keyrecorder.swift
Test:
* Reset global config Hotkeys, see Ctrl+Shift_L instead of Ctrl+Space, and Shift_L instead of empty.
* keyboard-us should have no long press options.
=> fix: default TriggerKeys; Shift_L display; hide long press options

webpanel/webpanel.cpp
This is same with https://github.com/fcitx-contrib/fcitx5-js/commit/8aee401093b36559e124a2aa8097409d30609838
Tested with rime-combo-pinyin and rime-ice. Arrow keys could move highlight in scroll mode.
=> fix: scroll mode resets on keyup

src/CMakeLists.txt, src/controller.swift, src/fcitx-public.h, src/tunnel.cpp, src/tunnel.h, webpanel/CMakeLists.txt, webpanel/tunnel.cpp, webpanel/webpanel.cpp
Pass UI settings directly from f5m to librime. The approach here is to define some variables in tunnel.cpp, and the dynlib loader will automatically resolve undefined symbols to the definitions in the main program. However, we have to pass some linker flags to silence linker complaints. I don't expect the mechanism to be used in the future, except for hacks like this.
1. Build and install the new f5m main program
2. Build and install the new librime (https://github.com/fcitx-contrib/fcitx5-macos-prebuilder/pull/44)
3. Build and install the new fcitx5-rime (https://github.com/fcitx-contrib/fcitx5-macos-plugins/pull/48)
4. Launch the new f5m
After this change, the new f5-rime plugin (shipped by f5m) will require the latest main program to function, or it won't be loaded (with an error …
=> Define tunnel variables for bypassing fcitx limitations

webpanel/webpanel.h
This PR adjusts the scroll key bindings to better align with the behavior of macOS's native input method. The changes include:
- **Expand**: Now triggered by both `=` and `▼` (Down arrow), consistent with macOS.
- **Collapse**: Now triggered by `-`.
- **Up**: Now triggered by both `-` and `▲` (Up arrow).
- **Down**: Now triggered by both `=` and `▼` (Down arrow).
=> Adjust scroll key bindings to match macOS native input method behavior

macosfrontend/macosfrontend-public.h, macosfrontend/macosfrontend.cpp, macosfrontend/macosfrontend.h, src/controller.swift
Fixes #204
I enabled CapsLock to switch to ABC. At first I thought this is a chinese-addons issue as rime clears preedit. Turns out that rime clears because it recognizes CapsLock. And if using Ctrl+Space then every engine leaves a dead client preedit.
fcitx5 executes engine's deactivate method when switching IM internally, which is good enough on Linux.
The commit and clear preedit have to be executed synchronously as next cycle f5m will lose the ability to do anything on client. Dummy preedit also needs explicit suppression.
=> respect engine's switch behavior on focus out

src/config/inputmethod.swift
Async operations on view model doesn't eliminate the bug. It only makes it intermittent.
Minimal reproducible view on macOS:
```swift
import SwiftUI
struct HeaderView: View {
let onDelete: () -> Void
var body: some View {
Text("Header")
.contextMenu {
Button {
onDelete()
} label: {
Text("Delete")
}
}
}
}
struct ContentView: View {
@State private var list = [String]()
var body: some View {
NavigationSplitView {
List {
ForEach(list, id: \.self) { item in
Section(header: HeaderView(onDelete: {
list.removeAll { $0 == item }
})) {
Text(item)
}
}
}
} detail: {
Text("Detail")
}.onAppear() {
list = ["Item 1", "Item 2", "Item 3"]
}
}
}
```
Without NavigationSplit or without header the crash won't happen. Absolutely a bug in SwiftUI.
=> fix: don't use removable Section header in NavigationSplit
